### ISSUE TITLE
Add lztr.me tracker

### ISSUE THREAD

**Issue by zamzamdesu** [mkgeeky/autodl-trackers#10]
Please add lztr.me tracker:
* Bot: Lagertha
* Channel: #lztr
* IRC: irc.lztr.me

Examples: https://privatebin.io/?37f83a6344babc23#EQTfr64MGfw7F6JMJmY4xPcXqhYTxBvAcyE6J1iVV4UX

**Comment by mkgeeky** [comment]
I'm so sorry, but have been offline due private issues.
If this issue still exists, please reopen.

//mkgeeky
