### ISSUE TITLE
Add Carpathians tracker

### ISSUE THREAD

**Issue by N1NCS** [mkgeeky/autodl-trackers#12]
Please add Carpathians tracker:

*Tracker name: Carpathians
*Tracker abbreviation: Carp
*Tracker IRC server address: irc2.hu
*Tracker IRC announce channel: #carpathians
*Tracker IRC announcer name: Carpathians

All further information can be found in the attachment.

[Carpathians.tracker.txt](https://github.com/mkgeeky/autodl-trackers/files/13793695/Carpathians.tracker.txt)

**Comment by mkgeeky** [comment]
https://github.com/mkgeeky/autodl-trackers/releases/tag/v290.6.6
