### ISSUE TITLE
[New Tracker] Animeworld

### ISSUE THREAD

**Issue by zip6como** [mkgeeky/autodl-trackers#18]
Please add Animeworld tracker

Name of the tracker: Animeworld
Name of the announce bot: ryuko
IRC network: irc.rizon.net:6697 (TSL)
channel: #animeworld (Has channel password)

There are 3 types of announces that get sent to the channel:
New Upload: [10 samples](https://pastebin.com/WZTP7g2A)
Torrent featured: [6 samples](https://pastebin.com/0fazBy1e)
Reseed request: [10 samples](https://pastebin.com/dzCEDwsT)
(Links expire in 7 days)
The Torrent featured announce only happens if the torrent wasn't already featured on upload and got featured later on.
If possible, I would find it awesome if Autodl-irssi could automatically download both types of featured torrents.

Thanks in advance!

**Comment by mkgeeky** [comment]
Hello @zip6como 

Can you please provide download URLs?
Without passkey etc.

If the download URLs is different for New Upload, Featured and Reseed, please provide all

**Comment by zip6como** [comment]
I am not sure what you mean by download URL. Isn't the download URL provided near the end of every announce?

**Comment by mkgeeky** [comment]
It's only for the details page.
I need a full download URL.
Right click at the download icon, and copy into here.
_Remember to remove your passkey_

**Comment by zip6como** [comment]
Okay, here is one:
https://animeworld.cx/torrents/download/39411

**Comment by mkgeeky** [comment]
@zip6como 
I have made a test. Not sure it's working.
So if you can download the .tracker file, add to your autodl-irssi and test it, before I put into main.
https://github.com/mkgeeky/autodl-trackers/blob/18-new-tracker-animeworld/trackers/AnimeWorld.tracker

**Comment by zip6como** [comment]
Thanks a lot! I will test the .tracker file and if it grabs both types of featured torrents.
This might take some time (a few weeks probably). You will hear again from me after the testing time.

**Comment by zip6como** [comment]
Hi again,
I tested the .tracker file in autodl-irssi, but it has some issues:

The .tracker file treats reseed requests as uploads and tries to grab them, which is bad.
When a torrent featured announce happens, it doesn't grab the torrent because the announce is missing the [Vorgestellt] tag.
And for some reason it doesn't match announces with the [Vorgestellt] tag, even in regular announces.

I hope that you can find some kind of solution.
Thanks again for your time and efforts.

**Comment by mkgeeky** [comment]
Hmm.
I kinda have a problem with the resed requests.
As I understand you, you wont to the download the upload? Or only if you have the files on your server?

Regarding the  **Vorgestellt** tag. I'll have a look at it in a courple of days.

**Comment by zip6como** [comment]
Yes, I want to download all featured torrents as soon as they get announced or uploaded.
That means any torrent whose announce starts with `Torrent vorgestellt:` or has the `[Vorgestellt]` tag in the "Neuer Upload:" announce.
It doesn't matter if the files are already on the server.

**Comment by mkgeeky** [comment]
Okay.
My thought is to remove the Reseed Request for now.

Can you please provide some more sample with the [Vorgestellt] tag?

**Comment by zip6como** [comment]
Here are all the announces I could get:
Announces with the [Vorgestellt] tag: [6 samples](https://pastebin.com/5frRw79S)
Announces without the [Vorgestellt] tag, but got featured at a later point: [10 samples](https://pastebin.com/3wg9ebWj)
(Links expire in 7 days)
The ones that got featured later all start with "Torrent vorgestellt:" but are missing the [Vorgestellt] tag.
It would be nice if it was possible to auto download both types of featured torrents.

**Comment by mkgeeky** [comment]
Have tried to update the .tracker file
Could you please test it, and get back to me
https://github.com/mkgeeky/autodl-trackers/blob/18-new-tracker-animeworld/trackers/AnimeWorld.tracker

**Comment by zip6como** [comment]
Thanks again. I will test the .tracker file. Please keep in mind that it might take a few weeks to test.

**Comment by zip6como** [comment]
Hi,

Sadly, it once again doesn't work. I guess it's not possible to autosnatch featured torrents. But the rest works, so I guess you can add it to the main branch.

Thanks for your efforts.

**Comment by mkgeeky** [comment]
Sorry to hear.
I have added the .tracker file to main branch.
However, I have tried to change the .tracker in Dev branch, with a new thing.
Could you try it out?

https://github.com/mkgeeky/autodl-trackers/blob/dev/trackers/AnimeWorld.tracker

**Comment by zip6como** [comment]
Sure, but what did you Change? (So i can test if it works)

**Comment by mkgeeky** [comment]
From
**linepatterns**
to
**multilinepatterns**

Hopeful it does both patterns work

**Comment by zip6como** [comment]
It should be working.
