### ISSUE TITLE
[New Tracker] FinElite

### ISSUE THREAD

**Issue by mobbi-dev** [mkgeeky/autodl-trackers#20]
Please add FinElite tracker

Tracker name: FinElite
Tracker IRC announcer name: FinElite
Tracker IRC server address: irc.predataba.se
Tracker IRC announce channel: #announce

[FinElite.tracker](https://github.com/mobbi-dev/autodl-trackers/blob/feature/FinElite/trackers/FinElite.tracker)

New Upload: [5 samples](https://pastebin.com/ZT5xt2X7)

Thanks!

**Comment by mkgeeky** [comment]
Will have a look at it, and release it into v290.6.9 later on 🙂
