### ISSUE TITLE
TorrentBytes error 301

### ISSUE THREAD

**Issue by kovacsr89** [mkgeeky/autodl-trackers#5]
Dear mkgeeky!

I trying to download torrent from TorrentBytes with autodl-irssi. I get this error:
Got HTTP 301, check your tracker settings for TorrentBytes!
I set the uid and pass for tracker settings. I see the announce channel, but fail to download the torrent.

Thanks,
kovacsr89

**Comment by mkgeeky** [comment]
Hello @kovacsr89
I don't have a account on TB, but I'll try to look into the problem.
If any have some solutions to this problem, your welcome to post it 👍

**Comment by kovacsr89** [comment]
A few lines from the announce channel:

09:51 <&ByteMe> [TB-RLS] .:. [ Experimento Quartermass-Farmoscopia-ES-CD-FLAC-2001-CEBAD ] .:. [ https://www.torrentbytes.net/download.php?id=3292898 ] .:. [ https://www.torrentbytes.net/details.php?id=3292898 ] .:. [ Uploaded 1 minute, 11 seconds after pre ]
09:52 <&ByteMe> [TB-RLS] .:. [ Machine.Gun.Kellys.Life.in.Pink.2022.720p.WEB.h264-OPUS ] .:. [ https://www.torrentbytes.net/download.php?id=3292899 ] .:. [ https://www.torrentbytes.net/details.php?id=3292899 ] .:. [ Uploaded 48 seconds after pre ]
09:53 <&ByteMe> [TB-RLS] .:. [ Red Wine-Suenos Y Locura-ES-CD-FLAC-2003-CEBAD ] .:. [ https://www.torrentbytes.net/download.php?id=3292900 ] .:. [ https://www.torrentbytes.net/details.php?id=3292900 ] .:. [ Uploaded 1 minute, 16 seconds after pre ]
09:56 <&ByteMe> [TB-RLS] .:. [ Forgotten.Fables.Wolves.On.The.Westwind-DARKZER0 ] .:. [ https://www.torrentbytes.net/download.php?id=3292901 ] .:. [ https://www.torrentbytes.net/details.php?id=3292901 ]
09:59 <&ByteMe> [TB-RLS] .:. [ MLB.2022.06.27.Pittsburgh.Pirates.vs.Washington.Nationals.720p.WEB.h264-SPORTSNET ] .:. [ https://www.torrentbytes.net/download.php?id=3292902 ] .:. [ https://www.torrentbytes.net/details.php?id=3292902 ] .:. [ Uploaded 4 minutes, 2 seconds after pre ]
10:01 <&ByteMe> [TB-RLS] .:. [ Only.Murders.in.the.Building.S02E02.German.DL.720p.WEB.h264-WvF ] .:. [ https://www.torrentbytes.net/download.php?id=3292903 ] .:. [ https://www.torrentbytes.net/details.php?id=3292903 ] .:. [ Uploaded 58 seconds after pre ]
10:02 <&ByteMe> [TB-RLS] .:. [ Gibbon.Beyond.The.Trees-DARKSiDERS ] .:. [ https://www.torrentbytes.net/download.php?id=3292904 ] .:. [ https://www.torrentbytes.net/details.php?id=3292904 ] .:. [ Uploaded 38 seconds after pre ]

**Comment by mkgeeky** [comment]
Thanks for the invite 💪
Will have a look at the issue asap 👍

**Comment by mkgeeky** [comment]
Hmm. Can't figure out why this isn't working 😢 
I'll keep trying to fix it. In the meanwhile, have a look at their RSS Feed or [autobrr](https://github.com/autobrr/autobrr)
