### ISSUE TITLE
UHD changed announce bot and format

### ISSUE THREAD

**Issue by gumbo32** [mkgeeky/autodl-trackers#7]
One of the trackers changed the format of their announcements and the announcer. I *think* I need to edit the tracker file more than just the announcer. Is this something I could get help with? I have changed the announcer to the new announcer through the trackerfile manually but it doesn't register the new announcer.

Info on the announcer and examples of the announce:
https://privatebin.io/?7f6aefc5af649d62#FxPp877Qrj7p7ZyXkhJyVg6NdsjgTFCixLHEFSmJdZV1

Old tracker file
[UHDBits.zip](https://github.com/mkgeeky/autodl-trackers/files/10200040/UHDBits.zip)

**Comment by gumbo32** [comment]
UHD is working on it.

**Comment by mkgeeky** [comment]
Even though you have closed this issue, I have updated UHDBits.tracker
Please return if there is any errors :)

**Comment by gumbo32** [comment]
Thank you!

I loaded the new UHDBits.tracker and restarted irssi. In the rtorrent plugin I see the error message:

https://i.imgur.com/0QIVLuU.png

**Comment by mkgeeky** [comment]
Hi,

Have updated UHDBits.tracker file. Now there should not be any error :)

**Comment by gumbo32** [comment]
gosh darnit, I'm sorry. The announce format was updated again. Do you mind working on this regex again? Thank you so much!

https://privatebin.io/?b1ff905b05b7fe1f#3V8dDYM3Z6Dw1TjnqjpxdAzFgqS7VaTY63bCHfmABXUe

**Comment by mkgeeky** [comment]
Updated in v290.6.2
Please update issue with an update :)

Merry Xmas 🎄
